name: generate animation

on:
  # tự động chạy mỗi 24 giờ
  schedule:
    - cron: "0 */24 * * *" 
  
  # cho phép chạy thủ công bất cứ lúc nào
  workflow_dispatch:
  
  # chạy mỗi khi có thay đổi trên nhánh main
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # vẽ con rắn từ đóng góp của user sjsjsmsmsj
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: sjsjsmsmsj
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # đẩy file đã vẽ lên nhánh 'output'
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
